select e1.ename, e1.empno, e1.sal, e2.ename, e2.empno, e2.sal
from emp e1, emp e2
where   e1.ename <> e2.ename and e1.sal < e2.sal
        and e1.job = 'PHILOSOPHER' and e2.job = 'ENGINEER';

CREATE INDEX EMP_JOB_TREE ON EMP(JOB);
ANALYZE INDEX EMP_JOB_TREE COMPUTE STATISTICS;
DROP INDEX EMP_JOB_TREE;

CREATE INDEX EMP_SAL_TREE ON EMP(SAL);  /* Non viene usato */
ANALYZE INDEX EMP_SAL_TREE COMPUTE STATISTICS;
DROP INDEX EMP_SAL_TREE;

CREATE INDEX EMP_ENAME_TREE ON EMP(ENAME);
ANALYZE INDEX EMP_ENAME_TREE COMPUTE STATISTICS;
DROP INDEX EMP_ENAME_TREE;

CREATE INDEX EMP_JOB_SAL_ENAME_TREE ON EMP(JOB,SAL,ENAME);
ANALYZE INDEX EMP_JOB_SAL_ENAME_TREE COMPUTE STATISTICS;
DROP INDEX EMP_JOB_SAL_ENAME_TREE;