CREATE MATERIALIZED VIEW CHIAMATE_INCASSI_MESE 
BUILD IMMEDIATE
REFRESH FORCE ON COMMIT
ENABLE QUERY REWRITE
AS
SELECT MESE, SUM(CHIAMATE), SUM(PREZZO)
FROM TEMPO T, FATTI F
WHERE T.ID_TEMPO=F.ID_TEMPO
GROUP BY MESE;