SELECT MESE, SUM(CHIAMATE) AS CHIAMATE_TOTALI, RANK() OVER (ORDER BY SUM(CHIAMATE) DESC)
FROM TEMPO T, FATTI F
WHERE T.ID_TEMPO=F.ID_TEMPO AND ANNO=2003
GROUP BY MESE;

SELECT MESE, CHIAMATE_MENSILI, RANK() OVER (ORDER BY CHIAMATE_MENSILI DESC)
FROM CHIAMATE_INCASSI_MESE
WHERE EXTRACT(YEAR FROM MESE)=2003;
(funzionerebbe se mese fosse nel formato corretto mm-yyyy, che non sembra ottenibile in oracle!
soluzione: 2 diversi campi con mese e anno)