CREATE OR REPLACE TRIGGER AggiornamentoSalari
AFTER UPDATE OF DNAME ON DIP
FOR EACH ROW
WHEN (old.DNAME='ACCOUNTING' AND new.DNAME='SALES')
BEGIN
    UPDATE IMP
    SET SAL=SAL+100
    WHERE DEPTNO=:new.DEPTNO;
END;
